train:
  datasets:
    - path: /rlwrld/jaehyun/datasets/egodex_retargeted/gr1/basic_pick_place
      embodiment_tag: egodex
      data_config: fourier_gr1_arms_waist
      weight: 1.0
    - path: "/rlwrld/heeseung/datasets/gr1_mg_gr00t_2400"
      embodiment_tag: new_embodiment
      data_config: fourier_gr1_arms_waist
      weight: 1.0