train:
  datasets:
    - path: /workspace/project/datasets/real_allex/20251208_170328_cubestack_lerobot
      embodiment_tag: new_embodiment
      data_config: allex_thetwo_46_ck16_egostereo_history_multi_frame
      weight: 1.0