train:
  datasets:
    - path: datasets/egodex_lerobot/v21_basic_pick_place_fixed
      embodiment_tag: egodex
      data_config: egodex_naive
      weight: 1.0

    - path: "/rlwrld/heeseung/datasets/gr1_mg_gr00t_2400"
      embodiment_tag: new_embodiment
      data_config: fourier_gr1_arms_waist
      weight: 1.0
