train:
  datasets:
    - path: /workspace/project/heeseung_datasets/20251205_155425_raise_hand_lerobot
      embodiment_tag: new_embodiment
      data_config: allex_thetwo_46_ck16_egosingle_history_multi_frame
      weight: 1.0