train:
  datasets:
    - path: /workspace/project/heeseung_datasets/20251127_163329_raisearm_lerobot
      embodiment_tag: new_embodiment
      data_config: allex_thetwo_46_ck16_egostereo_history
      weight: 1.0