train:
  datasets:
    - path: /workspace/project/heeseung_datasets/20251205_161601_wave_lerobot
      embodiment_tag: new_embodiment
      data_config: allex_thetwo_46_ck16_egostereo_history_multi_frame
      weight: 1.0